[package]
name = "etcd-workbench"
version = "1.2.0"
description = "Etcd Workbench"
authors = ["beifengtz"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["shell-open", "window-close", "window-hide", "window-maximize", "window-minimize", "window-show", "window-start-dragging", "window-unmaximize", "window-unminimize"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
window-shadows = "0.2.2"

tokio = { version = "1.38.0", features = ["full"] }
log = "0.4.22"
env_logger = "0.11.3"
dashmap = "6.0.1"
etcd-client = { version = "0.14.0",features = ["tls"] }
lazy_static = "1.5.0"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
